
import { supabase } from '@/integrations/supabase/client';

export async function findUserByEmail(email: string): Promise<string | undefined> {
  try {
    // Use a simplified query approach to avoid TypeScript type instantiation issues
    const { data, error } = await supabase
      .from('profiles')
      .select('id')
      .eq('email', email)
      .limit(1);
      
    if (error) throw error;
    return data && data.length > 0 ? data[0].id : undefined;
  } catch (error) {
    console.error('Error finding user by email:', error);
    return undefined;
  }
}

// Add the createUser function
export async function createUser(
  email: string,
  firstName: string,
  lastName: string,
  profileData: {
    cpf?: string;
    birthDate?: string;
    phone?: string;
    address?: string;
    addressNumber?: string;
    addressComplement?: string;
    neighborhood?: string;
    city?: string;
    state?: string;
    postalCode?: string;
  }
): Promise<string | undefined> {
  try {
    // First check if user already exists
    const existingUserId = await findUserByEmail(email);
    if (existingUserId) return existingUserId;
    
    // Create profile entry with UUID generated by Supabase
    const profileId = crypto.randomUUID();
    
    // Insert profile with a simplified approach
    const { error } = await supabase
      .from('profiles')
      .insert({
        id: profileId,
        email: email, // Add email to the profile table
        first_name: firstName,
        last_name: lastName,
        cpf: profileData.cpf,
        birth_date: profileData.birthDate,
        phone: profileData.phone,
        address: profileData.address,
        address_number: profileData.addressNumber,
        address_complement: profileData.addressComplement,
        neighborhood: profileData.neighborhood,
        city: profileData.city,
        state: profileData.state,
        postal_code: profileData.postalCode
      });
    
    if (error) throw error;
    return profileId;
  } catch (error) {
    console.error('Error creating user:', error);
    return undefined;
  }
}
