// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whbpiormdsldcqncshqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoYnBpb3JtZHNsZGNxbmNzaHF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNDYzNTksImV4cCI6MjA2MzYyMjM1OX0.e-e9sQfGjPNj8aAkedlOAsyNNbTTQZJGhPqECGa7TDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);