// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdztuiwaybcwogfidafy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkenR1aXdheWJjd29nZmlkYWZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NDA3MzksImV4cCI6MjA2MzIxNjczOX0.muh6utcEdsbK1sQbM7xfSkDWfdKIDV2bTRuEFtXtsWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);