
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgvqxeqjpkkfolyywxrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRndnF4ZXFqcGtrZm9seXl3eHJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMDkwNDUsImV4cCI6MjA1ODY4NTA0NX0.o04lcLCSPyZFSwqAQkedw5qF9rSBxPPSsFTn0AbDceQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: localStorage
    }
  }
);
